# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Niyang Bai
title: M.Sc. Economics at Uni Bonn
email: niyangbai@gmail.com
# website: https://github.com/niyangbai

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  niyangbai
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
flickr_username: 195567370@N08
# instagram_username: jameswgrant
linkedin_username: niyangbai
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Niyang and I'm a second year master student at Uni Bonn. I have worked at several companies gaining teamwork and leadership skills.
  I am most skilled in: <mark>Python</mark> and <mark>R</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: left
        title: Master's Thesis
        #link: https://github.com/niyangbai/wagegap22
        #link_text: For more information
        additional_links:
          - title:  wagegap22
            icon: fab fa-github
            url: https://github.com/niyangbai/wagegap22
          - title:  wagegap22package
            icon: fas fa-cube
            url: https://github.com/niyangbai/wagegap22package
        quote: >
          Does the minimum wage reduce the ethnic wage gap?
        description: | # this will include new lines to allow paragraphs
            Often, income inequality exists across ethnical groups. Minimum wages have long been seen as an important part of public policy to deal with poverty and this kind of inequality. I want to verify whether the minimum wage reduces the income gap between races.


      - layout: left
        title: Deep Learning Project
        #link: https://github.com/niyangbai/GameStopPrediction
        #link_text: For more information
        additional_links:
          - title: GameStopPrediction
            icon: fab fa-github
            url: https://github.com/niyangbai/GameStopPrediction
          #- title:  niyangbai/master_thesis
            #icon: fab fa-github
            #url: github.com/niyangbai/master_thesis
        quote: >
          Stock Price Prediction with Social Media Comments.
        description: | # this will include new lines to allow paragraphs
            In this project, I plan to use natural language data from r/wallstreetbets during the GameStop (NYSE: GME)'s short squeeze event to build a convolutional neural network, which can predict its stock prices, and then compare it with classic time series predictive models to check its validity.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shanghai Urban Real Estate Appraisal Co., Ltd.
        link: www.valuer.org.cn
        # link_text: www.valuer.org.cn
        sub_title: Assistant Appraiser
        caption: May 2020 - Oct 2020
        quote: >
          Real estate consulting, investment, and tender services in China.
        description: | # this will include new lines to allow paragraphs
          - participating in bids writing; 
          - crawling and cleaning historical data of land transaction; 
          - adjusting given models based on new data;
          - spatial analysis with GIS;
          - finial results visualization ; 
          - making part of the slides for finial report;
          
      - layout: left
        title: BARE International
        link: www.bareinternational.com
        # link_text: www.bareinternational.eu
        sub_title: Data Quality Specialist
        caption: Jul 2019 - Dec 2019
        quote: >
          BARE International was born from the need for mystery customer research at the national and global level.
        description: | # this will include new lines to allow paragraphs
          - taking part in market investigations;
          - assisting in data analysing and editing the final report for market investigations; 
          - checking the logic and understandability of questionnaire/ guidelines before the projects start; 
          - training and assigning tasks for part-time and home-based employees, helping them solve problems;

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Bonn
        caption: 2020 - 2022
        sub_title: MSc Economics
        quote: >
          The University of Bonn is internationally recognized as one of the leading research universities in Germany.
        description: | # this will include new lines to allow paragraphs
          - a two-year full-time quantitative and research oriented master's program
          - main courses including: Mathematics, Microeconomics, Macroeconomics, Econometrics, Dynamic Methods, Computational Statistics, Time Series and Labor Economics      
      - layout: left
        title: ENSAI
        caption: 2021 - 2022
        sub_title: Semester Abroad
        quote: >
          Ensai is the only major grande école d'ingénieurs entirely dedicated to the professions of statistical engineering and information processing.
        description: | # this will include new lines to allow paragraphs
          - the final year of the Engineer Statistician Program, with a specialization in ISTS (Ingénierie Statistique des Territoires et de la Santé)
          - main courses including: Machine Learning, Territorial Analysis, Economic Modeling and Advanced Econometrics

      - layout: left
        title: Shanghai Lixin University of Accounting and Finance
        caption: 2016 - 2020
        sub_title: BSc Economics
        quote: >
          Established in 1928 and was founded by the “Father of the Chinese Modern Accounting”, Mr. Pan Xulun.
        description: | # this will include new lines to allow paragraphs
          - a four-year full-time bachelor's program
          - main courses including: Advanced Mathematics, Linear Algebra, Statistics, Probability Theory, Microeconomics, Macroeconomics and Econometrics

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Economics and Statistics some of my other interests and hobbies are:
      - Soccer
      - Gaming
      - Music
      - Film Shooting
      
# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
